services:
  build-rms:
    build:
      context: .
      dockerfile: Dockerfile
    image: siahq2006/rms-docker-watchvault-img:v2
    container_name: rms-docker-container-watchvault
    ports:
      - "8000:5050"